#!/bin/bash
echo "Downloading the Docker Image"
docker run -p 6080:6080 -d colinhuang/wine-with-novnc > /dev/null 2>&1
echo "Downloaded, running"
echo "Updating for stability"
# docker exec -it $(docker ps -q) bash -c 'sudo add-apt-repository multiverse -y'  > /dev/null 2>&1
docker exec -it $(docker ps -q) bash -c 'sudo apt update && sudo apt install firefox -y'  > /dev/null 2>&1
echo "Updated, feel free to open web preview on port 6080"
echo "usually https://shell.cloud.google.com/devshell/proxy?authuser=0&port=6080&environment_id=default"
